agda/mdr/urls.py
from django.conf.urls import patterns

urlpatterns = patterns('mdr.views',
    (r'^mdr/$', 'top'),
    (r'^mdr/scan/$', 'scan'),
    (r'^mdr/search/$', 'search'),
    (r'^mdr/family/$', 'family_lookup'),
    (r'^mdr/family/(\w*)$', 'family_lookup'),

    (r'^api/mdr/scan/$', 'api_scan'),
    (r'^api/mdr/search/$', 'api_search'),
    (r'^api/mdr/family/$', 'api_family_lookup'),
)

agda/mdr/models.py
import json
import os
import shutil

from django.conf import settings
from django.db import models
from django.template.loader import render_to_string


from agda.models import Package
from agda.query import MySQLFulltextSearchQuerySet
from jobs.models import Job, slurm

import parse_mdrscan
from core import fasta ## This is only for copying, stupid.

mdr_package = Package(
    view='mdr.views.top',
    name='mdr',
    displayname='MDR',
    description='MDR family database and tools.')
mdr_package.register()

mdrscan_tool = mdr_package.new_tool(
    view='mdr.views.scan',
    results_view='mdr.views.scan_results',
    api_view='mdr.views.api_scan',
    name='mdr/mdrscan',
    displayname='MDRScan',
    description='Scan a sequence and classify any known present MDR domains.')

mdrsearch_tool = mdr_package.new_tool(
    view='mdr.views.search',
    api_view='mdr.views.api_search',
    name='mdr/mdrsearch',
    displayname='MDRSearch',
    description='Search the MDR database.')

mdrlookup_tool = mdr_package.new_tool(
    view='mdr.views.family_lookup',
    api_view='mdr.views.api_family_lookup',
    name='mdr/mdrlookup',
    displayname='MDRLookup',
    description='Show information on an MDR family.')


class MDRScanJob(Job):
    files = dict(query='query.fasta',
                 hmmpfam='mdrscan.hmmpfam',
                 json='mdrscan.json')

    tool = mdrscan_tool

    class Meta:
        permissions = (
            ("can_view", "Can view and submit mdr job"),
        )

    def on_submit(self, entries):
        self.statistics = json.dumps(dict(sequences=len(entries), residues=sum(len(e) for e in entries)))
        self.write_workfile('query', entries.to_str())
        script = 'mdrscan.sh'
        db = os.path.join(settings.DATA_ROOT, 'pub', 'mdr', '2010.1', 'mdr.pfam.gz')
        self.write_workfile(script, render_to_string('mdr/mdrscan.sh', dict(db=db)))
        self.write_workfile('family_data.json', parse_mdrscan.FamilyData.dumps(Family.objects.all()))
        shutil.copy(parse_mdrscan.__file__.rstrip('oc'), self.workdir)

        ## Copy the care/fasta.py thingy TODO fix this
        self.make_workdir('core')
        shutil.copy(fasta.__file__.rstrip('oc'), os.path.join(self.workdir, 'core'))
        self.write_workfile('core/__init__.py', "")

        self.result_files = self.files
        slurm.submit(self, self.workfile(script))


class Family(models.Model):
    id = models.CharField(max_length=10, primary_key=True)
    name = models.CharField(max_length=10)
    representative_description = models.TextField(blank=True, null=True)
    representative_id = models.CharField(max_length=12)
    size = models.IntegerField()
    swissprot_members = models.IntegerField()
    average_pcid = models.FloatField()
    in_human = models.BooleanField()
    in_kingdom_eukaryota = models.BooleanField()
    in_kingdom_bacteria = models.BooleanField()
    in_kingdom_archaea = models.BooleanField()
    in_division_unassigned = models.BooleanField()
    in_division_synthetic = models.BooleanField()
    in_division_environmental_samples = models.BooleanField()
    in_division_phages = models.BooleanField()
    in_division_viruses = models.BooleanField()
    in_division_bacteria = models.BooleanField()
    in_division_plants = models.BooleanField()
    in_division_invertebrates = models.BooleanField()
    in_division_vertebrates = models.BooleanField()
    in_division_mammals = models.BooleanField()
    in_division_rodents = models.BooleanField()
    in_division_primates = models.BooleanField()
    zn1 = models.FloatField()
    zn2 = models.FloatField()
    nad = models.FloatField()
    nadp = models.FloatField()
    min_score = models.FloatField()
    max_score = models.FloatField()

    def __str__(self):
        if self.name:
            return self.id + ' - ' + self.name
        return self.id


class Member(models.Model):
    family_id = models.CharField(max_length=10)
    rank = models.IntegerField()
    family_name = models.CharField(max_length=10)
    source_database = models.CharField(max_length=16)
    uniprot_ac = models.CharField(max_length=6)
    uniprot_id = models.CharField(max_length=12)
    start = models.IntegerField()
    stop = models.IntegerField()
    score = models.FloatField()
    sequence_length = models.IntegerField()
    species = models.TextField()
    species_common_name = models.TextField(blank=True, null=True)
    kingdom = models.CharField(max_length=1)
    taxonomic_division = models.CharField(max_length=3)
    description = models.TextField(blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    objects = MySQLFulltextSearchQuerySet.as_manager()
    fulltext_indexes = dict(description=(description,),
                            default=(family_id,
                                     family_name,
                                     source_database,
                                     uniprot_ac,
                                     uniprot_id,
                                     species,
                                     species_common_name,
                                     description,
                                     comment))

    def __str__(self):
        return "%s - %s" % (self.family_id, self.rank)

agda/mdr/views.py
import json
import time

from django import forms
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.db import transaction
from django.http import (Http404,
                         HttpResponse, StreamingHttpResponse)
from django.shortcuts import (get_object_or_404,
                              redirect,
                              render)
from django.template import RequestContext
from django.utils.text import get_text_list

from agda.forms import (CleanFulltext,
                        DynamicSearchForm,
                        FastaCleaner,
                        FormContents,
                        clean_int_range,
                        clean_kingdom,
                        clean_species_code,
                        clean_taxonomic_division,
                        clean_wildcard_like,
                        fulltext_search_help,
                        get_dynamic_search_form_data,
                        get_form,
                        get_parameter_errors,
                        range_help,
                        wildcard_like_help)
from agda.forms.cached_uploads import CachedUploadManager

from agda.settings.local import SITE_ROOT
from agda.utils import (abspath,
                        model_dict)
from agda.views import (json_response,
                        package_template_dict,
                        render_and_split,
                        script_data,
                        stream)

from jobs.views_api import api_show_results

from jobs.models import (JOB_STATUS_LEVEL_ACCEPTED,
                         JOB_STATUS_LEVEL_FINISHED,
                         get_job_or_404)

from models import (Family,
                    MDRScanJob,
                    Member,
                    mdr_package,
                    mdrlookup_tool,
                    mdrscan_tool,
                    mdrsearch_tool)
import parse_mdrscan
import scan_examples


def mdr_params(request, *args, **kw):
    return package_template_dict(request, mdr_package, *args, **kw)


def mdrscan_params(*args, **kw):
    return mdr_params(*args, tool=mdrscan_tool, **kw)


def mdrsearch_params(*args, **kw):
    return mdr_params(*args, tool=mdrsearch_tool, **kw)


def mdrlookup_params(*args, **kw):
    return mdr_params(*args, tool=mdrlookup_tool, **kw)


def top(request):
    return render(request, 'agda/package-page.html', mdr_params(request))

### Scan ###

clean_fasta = FastaCleaner(default_id='query_sequence', min_sequences=0).clean


class MDRScanForm(forms.Form):
    name = forms.CharField(max_length=100, initial='MDRScan job', help_text='Job name')
    query = forms.CharField(widget=forms.Textarea(attrs={'class': 'query-sequence'}),
                            help_text='One or more fasta format sequences',
                            required=False)
    query_file = forms.FileField(help_text='One or more fasta format sequences', label='', required=False)

    annotations = dict(
        examples=dict(query=scan_examples.adh1a_human,
                      name='MDRScan example'),
        advanced=['name'])

    _entries = None

    def clean_query(self):
        self._entries = clean_fasta(self.cleaned_data['query'])
        return self._entries

    def clean_query_file(self):
        upload = self.cleaned_data['query_file']
        if upload is False or upload is self.initial['query_file']:
            # ClearableFileInputs return False for "clear" and initial data for
            # "keep".  Any initial data is already clean, so let cached_upload
            # sort these out.
            return upload
        self._entries = clean_fasta(upload)
        return upload

    def clean(self):
        cleaned_data = super(MDRScanForm, self).clean()
        plaintext = cleaned_data.get('query')
        file = cleaned_data.get('query_file')
        if plaintext and file:
            self._errors.setdefault('query', []).append('Please give sequences in plain text or upload a file, not both.')
        if 'query' not in self._errors and 'query_file' not in self._errors and not (plaintext or file):
            self._errors.setdefault('query', []).append('At least one sequence is required.')
        return cleaned_data

    def get_query_entries(self):
        if not self.is_valid():
            raise KeyError('Cannot get entries from invalid form')
        if self._entries is not None:
            return self._entries
        return self.clean_fasta(self.initial['query_file'].open())


@transaction.atomic
def api_scan(request):
    if request.method == 'GET':
        return json_response(dict(query='Sequence(s) in fasta format.', name='A name for your job (optional)'))
    try:
        data = json.loads(request.body)
    except:
        return HttpResponse(status=400)
    try:
        entries = clean_fasta(data['query'])
    except ValidationError, e:
        return json_response(dict(complaints=str(e)), status=422)
    job = MDRScanJob(status=JOB_STATUS_LEVEL_ACCEPTED)
    job.save()
    job = MDRScanJob.objects.select_for_update().get(pk=job.id)
    job.log_create(request.agda_api_user, 'Created in api.')
    job.submit(request.agda_api_user, request.META['REMOTE_ADDR'], data.get('name'), entries)
    return redirect(api_show_results, job.slug)


@transaction.atomic
def scan(request):
    key_base = 'mdrscan.submit_job'
    cached_uploads = CachedUploadManager.get_from_session(request.session, key_base, ['query_file'])
    ok_to_accept, form = get_form(MDRScanForm, request, cached_uploads)
    if not ok_to_accept:
        cached_uploads.store_in_session()
        form_contents = FormContents(form, **form.annotations)
        return render(request, 'mdr/scan.html', mdrscan_params(request, form_contents=form_contents))
    # Job accepted
    job = MDRScanJob(status=JOB_STATUS_LEVEL_ACCEPTED)
    job.save()
    job = MDRScanJob.objects.select_for_update().get(pk=job.id)
    job.log_create(request.user, 'Created in web interface.')
    entries = form.get_query_entries()
    job.submit(request.user, request.META['REMOTE_ADDR'], form.cleaned_data['name'], entries)
    cached_uploads.clear_from_session()
    return redirect('jobs.views.show_results', job.slug)


def _scan_results_preprocess(params, results, width):
    for confidence in results:
        for query in results[confidence]:
            for family in query['families']:
                for hit in family['hits']:
                    hit['graphic_margin'] = int(float(hit['first']) / query['length'] * width)
                    hit['graphic_width'] = int(float(hit['last'] - hit['first'] + 1) / query['length'] * width)
    params['graphic_width'] = width
    params['results'] = list(sorted(results.items()))
    params['summary'] = dict(
        strong_hits=sum(len(q['families']) for q in results['strong_hits']),
        weak_hits=sum(len(q['families']) for q in results['weak_hits']),
        queries=len(results['strong_hits'])
    )


def scan_results(request, slug=None):
    job = get_job_or_404(slug=slug, select_for_update=True)
    job.update_status(request.user)
    params = mdrscan_params(request, job=job)
    if job.status == JOB_STATUS_LEVEL_FINISHED:
        width = 200
        info = json.load(open(job.resultfile('json')))
        if info['format'] == parse_mdrscan.json_format_version:
            results = info['results']
        else:
            results = parse_mdrscan.parse_mdrscan(job.resultfile('hmmpfam'), job.resultfile('query'))
        _scan_results_preprocess(params, results, width)
    elif job.is_alive:
        reload_time, interval = request.session.setdefault('mdrscan', dict()).pop(job.slug, (0, 5))
        if reload_time <= time.time():
            reload_time = max(time.time() + 5, reload_time + interval)
            interval *= 2
        request.session['mdrscan'][job.slug] = (reload_time, interval)
        request.session.modified = True
        params.update(timeout=reload_time - time.time())
        params.update(reload_time=reload_time, interval=interval)
    return render(request, 'mdr/scan-results.html', params)


### Search ###

def to_mdr_family_id(family_id):
    if family_id.isdigit():
        number = int(family_id.lstrip('0'))
    elif family_id[:3].upper() != 'MDR':
        raise ValueError
    else:
        number = int(family_id[3:].lstrip('0'))
    if not (1 <= number <= Family.objects.count()):
        raise ValueError
    return 'MDR%03d' % number


def clean_family_id(queryset, field_name, value):
    values = value.split()
    q = []
    for value in values:
        try:
            family_id = to_mdr_family_id(value)
        except:
            raise ValidationError('Ids must be on the form MDR001, or a number.')
        q.append(Q(**{field_name: family_id}))
    return queryset.filter(reduce(lambda a, b: a | b, q))


def clean_source_database(queryset, field_name, value):
    value = value.strip().lower()
    sprot = ['sp', 'sprot', 'swissprot', 'swiss-prot']
    trembl = ['tr', 'trembl']
    if value in trembl:
        value = 'tr'
    elif value in sprot:
        value = 'sp'
    else:
        raise ValidationError('Please use one of %s.' % get_text_list(sprot + trembl))
    return queryset.filter(**{field_name: value})

clean_fulltext = CleanFulltext(dict(description='description')).clean

search_parameters = (
    ('all_text', 'All text', 'Fulltext search all textual fields. ' + fulltext_search_help, clean_fulltext),
    ('description', 'Description', 'Fulltext search sequence descriptions. ' + fulltext_search_help, clean_fulltext),
    ('family_id', 'Family ID', 'One or more MDR family ids.', clean_family_id),
    ('family_name', 'Family name', 'One or more MDR family names. ' + wildcard_like_help),
    ('source_database', 'Source database', 'Sequence origin; trembl or swissprot.', clean_source_database),
    ('uniprot_ac', 'Uniprot AC', 'One or more UniProtKB accession numbers. ' + wildcard_like_help),

agda/mdr/templates/mdr/lookup-results.html
{% extends "agda/package-page.html" %}

{% block title %}MDR family details{% endblock title %}
{% block content_title %}MDR family details{% endblock content_title %}

{% block stylesheet %}
{{ block.super }}
<link rel="stylesheet" href="{{ STATIC_URL }}css/mdr/family-list.css" />
{% endblock stylesheet %}

{% block extra_js %}
{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}scripts/mdr/toggle-show-members.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}scripts/mdr/hit-counter.js"></script>
{% endblock extra_js %}

{% block content %}
<div class="mdrsearch-status"></div>
<script>
	HierarchicalHitCounter(document, 
		['.member', '.family'], 
		['member', 'family'], 
		['.mdrsearch-status-family', '.mdrsearch-status'], 
		[' ({1}{0})', 'Searching{0} found {1} {2} in {3} {4}.'], 
		[' ({1})', 'Done. Found {1} {2} in {3} {4}.']).auto_update().done_when_ready();
</script>
{{ hits|safe }} 
{% endblock content %}

agda/mdr/templates/mdr/lookup.html
{% extends "agda/tool-page.html" %}

{% block title %}{{ block.super }}{% endblock title %}
{% block page-title %}MDR family lookup{% endblock page-title %}

{% block content %}
<div class="editform">
<form method="get" id="lookup-form">
{% csrf_token %}
<ul class="errorlist">{% for e in form_contents.form.non_field_errors %}<li>{{ e }}</li>{% endfor %}</ul>
<table class="fieldlist">
<col><col><col width="100%">
	{% for field in form %}{% include "agda/forms/table_form_field.html" with field=field %}{% endfor %}
	<tr><td></td>
		<td colspan="2">
			<ul class="buttons">
			  <li><button type="submit" title="Get MDR family">Go</button></li>
			</ul>
		</td>
	</tr>
</table>
</form>
<script> 
	$("#lookup-form").submit(function () {
		location.href = $('#id_family_id').val();
		return false;
	});
</script>
</div>
{% endblock content %}

agda/mdr/templates/mdr/scan-results.html
{% extends "agda/job/results.html" %}

{% block extra_css %}
{{ block.super }}
<link rel="stylesheet" href="{{ STATIC_URL }}css/mdr/mdr.css" />
{% endblock extra_css %}

{% block sidebar %}
{% if job.status == job_status.finished %}
	<h4>Result files</h4>
	<ul class='sidebar-links'>
	<li><a href="{{ job.resultdir_url }}{{ job.result_files.hmmpfam }}">Plaintext</a></li>
	<li><a href="{{ job.resultdir_url }}{{ job.result_files.json }}">Json</a></li>
	<li><a href="{{ job.resultdir_url }}{{ job.result_files.query }}">Query fasta</a></li>
	</ul>
{% endif %}
{{ block.super }}
{% endblock sidebar %}

{% block content_finished %}
<p>Found {{ summary.strong_hits|default:'no' }} significant match{{ summary.strong_hits|pluralize:'es' }} and {{ summary.weak_hits|default:'no' }} 
non-significant (detectable but insufficiently scoring) match{{ summary.weak_hits|pluralize:'es' }} in {{ summary.queries }} query sequence{{ summary.queries|pluralize }}.

{% for confidence, queries in results %}
	<div class="{{ confidence }}">
	{% if confidence == 'weak_hits' %}
		{% if summary.weak_hits %} 
			<p>
			<a onclick='toggle_display(this, "div.weak_hits", "div.hit_list")' href="javascript:void(0);" title="Click to show/hide hits below the score thresholds.">
				Show/hide {{ summary.weak_hits }} match{{ summary.weak_hits|pluralize:'es' }} below score thresholds
			</a>
		{% endif %}
		<div class="hit_list" style="display: none">
		<div style='padding-top: 2em'></div>
		<h3>Matches below score thresholds</h3>
		<p>These matches indicate detectable similarity between a query and a family, but with insufficient score to qualify for proper membership.   
	{% endif %}
	{% for query in queries %}
		<h3>Results for {% if not queries|length_is:1 %} sequence {{ forloop.counter }} &ndash;{% endif %} {{ query.id }}</h3>

		{% if not query.families %}<p>No matches found.{% endif %}

		<ul class="family-list">
		{% for family in query.families %}
			<li class="family">

				<h4>
					<a href="{% url 'mdr.views.family_lookup' family.id %}">{{ family.id }}{% if family.name %} &ndash; {{ family.name }}{% endif %}</a>
					<span class="description" title="Description of a representative sequence">{{ family.representative_description }}</span>
				</h4>
				<ul class="inline">
					<li>Family size: {{ family.size }}</li>
					<li>Member scores: {{ family.min_score|floatformat }}&ndash;{{ family.max_score|floatformat }}</li>
				</ul>
				<ul class="hit-list">
				{% for hit in family.hits %}
					<li>
						<div class="domain-graphic" style="width: {{ graphic_width }}px;">
							<div class="backbone"> </div>
							<a href="{% url 'mdr.views.family_lookup' family.id %}"><div class="domain{% if confidence == 'strong_hits' %} member{% endif %}" style="margin-left: {{ hit.graphic_margin }}px; width: {{ hit.graphic_width }}px;"><div class="label">{{ family.id }}</div></div></a>
						</div>
						<ul class="inline">
							<li>Score: {{ hit.score }} ({{ hit.margin|floatformat }} &times; {{ family.min_score|floatformat }})</li>
							<li>E-value: {{ hit.evalue }}</li>
							<li>Region: {{ hit.first }}&ndash;{{ hit.last }} ({{ hit.length }}aa)</li>
						</ul>
					</li>
				{% endfor %}
				</ul>
			</li>
		{% endfor %}
		</ul>
	{% endfor %}
	{% if confidence == 'weak hits' and summary.weak_hits %}
		</div> 
	{% endif %}	
	</div>	
{% endfor %}
{% endblock content_finished %}

agda/mdr/templates/mdr/scan.html
{% extends "agda/tool-page.html" %}

{% block title %}{{ tool.displayname }} Submit job{% endblock title %}

{% block content %}
<p>Scan a peptide sequence to find and classify any known MDR domains. Please give sequences in fasta format. 
<p>You can also <a onclick="resetValues($('#scan_form')[0], 'example')" title="Insert example values" href="javascript:void(0);">use some example data</a>, 
or <a title="Insert example values" href="javascript:void(0);" onclick="resetValues($('#scan_form')[0])">reset the form</a> to default values.  

{% include "agda/forms/table_form.html" with form_id="scan_form" form_heading="Submit new job" submit_button_text="Submit job" %} 

{% endblock content %}

agda/mdr/templates/mdr/search-family.html
{% load percentage %}
<div class='family'>
	<h4>{{ family.id }}{% if family.name %} - {{ family.name }} {% endif %}<span title="Description of a representative sequence">{{ family.representative_description }}</span></h4>
	<div class="columns">
		<div class="column">
			<span class="property">Representative: <span><a href="http://www.uniprot.org/uniprot/{{ family.representative_id }}" target="_new">{{ family.representative_id }}</a></span></span>
			<span class="property" title="Known member domains">Members: <span>{{ family.size }}</span></span>
			<span class="property" title="Known member domains in Swiss-Prot">Swiss-Prot: <span>{{ family.swissprot_members }}</span></span>
			<span class="property" title="Score range among known family domains">Member Scores: <span>{{ family.min_score|floatformat:2 }}&nbsp;&mdash;&nbsp;{{ family.max_score|floatformat:2 }}</span></span>
			<span class="property" title="Average percent pairwise identities">PCID: <span>{{ family.average_pcid|floatformat:2 }}%</span></span>
			<span class="property" title="Appears to bind Zn1 (catalytic)">Zn1: <span>{{ family.zn1|percentage }}</span></span>
			<span class="property" title="Appears to bind Zn2 (structural)">Zn2: <span>{{ family.zn2|percentage }}</span></span>
			<span class="property" title="Appears to bind NAD">NAD: <span>{{ family.nad|percentage }}</span></span>
			<span class="property" title="Appears to bind NADP">NADP: <span>{{ family.nadp|percentage }}</span></span>
		</div>
		<div class="column">
			<h3>Presence in kingdoms</h3>
			<table cellspacing="0" class="kingdoms">
				<tr>
					<th><span title="Human">Human</span></th>
					<th><span title="Eukaryota">Eukaryota</span></th>
					<th><span title="Bacteria">Bacteria</span></th>
					<th><span title="Archaea">Archaea</span></th>
				</tr>
				<tr>
					{% if family.in_human %}<td title="Present in human." class="present">Y{% else %}<td title="Absent in human." class="absent">N{% endif %}</td>
					{% if family.in_kingdom_eukaryota %}<td title="Present in eukaryota." class="present">Y{% else %}<td title="Absent in eukaryota." class="absent">N{% endif %}</td>
					{% if family.in_kingdom_bacteria %}<td title="Present in bacteria." class="present">Y{% else %}<td title="Absent in bacteria." class="absent">N{% endif %}</td>
					{% if family.in_kingdom_archaea %}<td title="Present in archaea." class="present">Y{% else %}<td title="Absent in archaea." class="absent">N{% endif %}</td>
				</tr>
			</table>
		
			<h3>Presence in taxonomic divisions</h3>
			<table cellspacing="0" class="divisions">
				<tr>
					<th><span title="Unassigned">una</span></th>
					<th><span title="Synthetic">syn</span></th>
					<th><span title="Environmental samples">env</span></th>
					<th><span title="Phages">pha</span></th>
					<th><span title="Viruses">vir</span></th>
					<th><span title="Bacteria">bct</span></th>
					<th><span title="Plants">pla</span></th>
					<th><span title="Invertebrates">inv</span></th>
					<th><span title="Vertebrates">ver</span></th>
					<th><span title="Mammals">mam</span></th>
					<th><span title="Rodents">rod</span></th>
					<th><span title="Primates">pri</span></th>
				</tr>
				<tr>
					{% if family.in_division_unassigned %}<td title="Present in taxonomic division unassigned." class="present">Y{% else %}<td title="Absent in taxonomic division ." class="absent">N{% endif %}</td>
					{% if family.in_division_synthetic %}<td title="Present in taxonomic division synthetic." class="present">Y{% else %}<td title="Absent in taxonomic division synthetic." class="absent">N{% endif %}</td>
					{% if family.in_division_environmental_samples %}<td title="Present in taxonomic division environmental samples." class="present">Y{% else %}<td title="Absent in in taxonomic division environmental samples." class="absent">N{% endif %}</td>
					{% if family.in_division_phages %}<td title="Present in taxonomic division phages." class="present">Y{% else %}<td title="Absent in taxonomic division phages." class="absent">N{% endif %}</td>
					{% if family.in_division_viruses %}<td title="Present in taxonomic division viruses." class="present">Y{% else %}<td title="Absent in taxonomic division viruses." class="absent">N{% endif %}</td>
					{% if family.in_division_bacteria %}<td title="Present in taxonomic division bacteria." class="present">Y{% else %}<td title="Absent in taxonomic division bacteria." class="absent">N{% endif %}</td>
					{% if family.in_division_plants %}<td title="Present in taxonomic division plants." class="present">Y{% else %}<td title="Absent in taxonomic division plants." class="absent">N{% endif %}</td>
					{% if family.in_division_invertebrates %}<td title="Present in taxonomic division invertebrates." class="present">Y{% else %}<td title="Absent in taxonomic division invertebrates." class="absent">N{% endif %}</td>
					{% if family.in_division_vertebrates %}<td title="Present in taxonomic division vertebrates." class="present">Y{% else %}<td title="Absent in taxonomic division vertebrates." class="absent">N{% endif %}</td>
					{% if family.in_division_mammals %}<td title="Present in taxonomic division mammals." class="present">Y{% else %}<td title="Absent in taxonomic division mammals." class="absent">N{% endif %}</td>
					{% if family.in_division_rodents %}<td title="Present in taxonomic division rodents." class="present">Y{% else %}<td title="Absent in taxonomic division rodents." class="absent">N{% endif %}</td>
					{% if family.in_division_primates %}<td title="Present in taxonomic division primates." class="present">Y{% else %}<td title="Absent in taxonomic division primates." class="absent">N{% endif %}</td>
				</tr>
			</table>
		</div>
	</div>
	<div class="members" id="members_{{ family.family_id }}">
		<h3><a onClick="toggle_show_members(this)" href="javascript:void(0);" title="Click to show/hide list of members">Show matching members<span class="mdrsearch-status-family"></span></a></h3>
		<div class="list">
			{{ members|safe }}
		</div>
	</div>
</div>
	

agda/mdr/templates/mdr/search-results.html
{% extends "agda/tool-page.html" %}

{% block title %}{{ tool.displayname }} Results{% endblock title %}
{% block content_title %}{{ tool.displayname }}{% endblock content_title %}

{% block stylesheet %}
{{ block.super }}
<link rel="stylesheet" href="{{ STATIC_URL }}css/mdr/family-list.css" />
{% endblock stylesheet %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}scripts/mdr/toggle-show-members.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}scripts/mdr/hit-counter.js"></script>
{% endblock scripts %}

{% block content %}
{{ hits|safe }} 
{% endblock content %}