agda/agda/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('agda.views',
    url(r'^$', 'top'),
    url(r'^contact$', 'contact'),
    url(r'^new_user$', 'new_user'),
    url(r'^admin/', include(admin.site.urls)),

    (r'^review_cached_upload/tmp([A-Za-z0-9_]{6})/$', 'review_cached_upload'),

    (r'^packages/$', 'list_packages'),
    (r'^tools/$', 'list_tools'),

    (r'^api/$', 'api_list_tools'),
    (r'^api/tools/$', 'api_list_tools'),
)

### Plugins ###

urlpatterns += patterns('',
    ('^results/', include('jobs.urls')),
    ('^api/results/', include('jobs.urls_api')),
    ('', include('profiles.urls')),
    ('', include('mdr.urls')),
    ('', include('datisca.urls')),
    ('', include('pconsc.urls')),
    ('speciesgeocoder', include('species_geo_coder.urls')),
)

agda/mdr/urls.py
from django.conf.urls import patterns

urlpatterns = patterns('mdr.views',
    (r'^mdr/$', 'top'),
    (r'^mdr/scan/$', 'scan'),
    (r'^mdr/search/$', 'search'),
    (r'^mdr/family/$', 'family_lookup'),
    (r'^mdr/family/(\w*)$', 'family_lookup'),

    (r'^api/mdr/scan/$', 'api_scan'),
    (r'^api/mdr/search/$', 'api_search'),
    (r'^api/mdr/family/$', 'api_family_lookup'),
)

agda/profiles/views.py
import logging

from django.views.generic import UpdateView
from braces.views import LoginRequiredMixin

from django import forms
from django.conf import settings
from django.contrib import (auth,
                            messages)
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.core.exceptions import ValidationError
from django.shortcuts import (redirect,
                              render)
from django.utils.html import mark_safe
from django.views.decorators.cache import never_cache

from agda.forms import (change_message_from_form,
                        get_form)

from agda.utils import (ModelDiffer,
                        get_initial)
from agda.views import (top,
                        require_nothing)


from .models import (AgdaUser,
                     email_max_length)

from .forms import AgdaUserEditForm

from profiles.utils import get_cracklib_complaints

logger = logging.getLogger(__name__)


class AgdaUserUpdateView(LoginRequiredMixin, UpdateView):
    # model=AgdaUser
    form_class = AgdaUserEditForm

    def get_object(self):
        return AgdaUser.objects.get(username=self.request.user)


### Login and logout ###
@never_cache
@require_nothing
def login(request):
    """Handle login."""
    login_successful, form = get_form(LoginForm, request)
    if login_successful:
        messages.success(request, "You are now logged in.")
        return login_success(request, form.cleaned_data['user'], form.cleaned_data['profile'], "password")
    return render(request, 'profiles/login.html', dict(form=form, next=request.GET.get('next', '')))


def login_success(request, user, profile, login_method):
    auth.login(request, user)
    logger.info("%s: logged in using %s (%s)" %
            (user.email, login_method, request.session['_auth_user_backend']))
    redirect_target = request.POST.get('next', 'agda.views.top')
    if redirect_target == '':
        redirect_target = 'agda.views.top'
    response = redirect(redirect_target)
    # Remember how we logged in, and that we are now no longer redirected for logging in
    response.set_cookie("last_login_type", login_method, max_age=365 * 24 * 60 * 60)
    request.session['redirected_to_login'] = False
    return response


@never_cache
@require_nothing
def logout(request):
    """Handle logout."""
    logger.info("%s: logged out." % (request.user.email))
    auth.logout(request)
    messages.success(request, "You are now logged out.")
    return redirect('agda.views.top')


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=email_max_length)
    password = forms.CharField(max_length=email_max_length, widget=forms.PasswordInput(render_value=True))

    def clean(self):
        """Populates cleaned data dict with user and profile on login success."""
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        if not email and password:
            return
        user = auth.authenticate(username=email, password=password)
        if user and user.is_active:
            try:
                profile = user
                if profile:
                    # This is the only code path to login success.
                    self.cleaned_data.update(user=user, profile=profile)
                    return self.cleaned_data
                else:
                    self._errors.setdefault('__all__', []).append('This user is not authorized.')
                    logger.warn("%s: tried to login but is not authorized." % email)
            except profile.DoesNotExist:
                self._errors.setdefault('__all__', []).append('This user has no profile.')
                logger.warn("%s: tried to login but is not connected to a profile." % email)
        else:
            self._errors.setdefault('__all__', []).append('Invalid username or password.')
            logger.warn("%s: failed to login." % email)
        # At this point login has failed and we return None.
        return None


### Account management ###
def clean_email(form):
    value = form.cleaned_data['email']
    if value == form.initial.get('email'):
        raise ValidationError('It is the same as the old address.')
    if User.objects.filter(email=value).count() != 0:
        msg = mark_safe('The email address is already in use: '
                        '<a href="%s" class="important">Get access to your existing account</a>')
        raise ValidationError(msg)
    return value


def form_clean_password(form):
        if form.cleaned_data.get("password1", ""):
            if form.cleaned_data.get("password1", "") != form.cleaned_data.get("password2", ""):
                for i in (1, 2):
                    form._errors.setdefault('password%d' % i, []).append("Passwords do not match.")
            else:
                complaints = get_cracklib_complaints(form.cleaned_data.get("password1", ""))
                if complaints:
                    form._errors.setdefault('password1', []).append("Bad password: %s." % complaints)
        return form.cleaned_data


class AccountChangeEmailForm(forms.Form):
    email = forms.EmailField(max_length=email_max_length)

    def clean_email(self):
        return clean_email(self)


class AccountNewPasswordForm(forms.Form):
    # Max password length same as User.email max_length
    password1 = forms.CharField(max_length=email_max_length, widget=forms.PasswordInput(render_value=True), label="New Password")
    password2 = forms.CharField(max_length=email_max_length, widget=forms.PasswordInput(render_value=True), label="New Password (again)")

    def clean(self):
        return form_clean_password(self)


class AccountChangeBasicInformationForm(forms.Form):
    # Name max length same as User.*_name max_length
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)


class AccountCreateForm(forms.Form):
    email = forms.EmailField(max_length=email_max_length)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    password1 = forms.CharField(max_length=email_max_length, widget=forms.PasswordInput(render_value=True), label="Password")
    password2 = forms.CharField(max_length=email_max_length, widget=forms.PasswordInput(render_value=True), label="Password (again)")

    annotations = dict(
        comments=dict(email='This will also be your Agda username. You will have to confirm this address by following a link in an email sent to it.')
        )

    def clean_email(self):
        return clean_email(self)

    def clean(self):
        return form_clean_password(self)


@never_cache
@login_required
def account_change_email(request):
    user = request.user
    profile = user
    ok_to_save, form = get_form(AccountChangeEmailForm, request)
    if not ok_to_save:
        if not form.initial:
            email = user.email
            form.initial['email'] = email
        return render(request, 'agda/account/change_email.html', dict(form=form))
    profile.save()
    profile.log_change(request.user, message="Agda: email change to %s requested" % profile.email)
    profile.send_email("Confirm your Agda email address change",
                       "agda/account/confirm_change_email.txt",
                       use_email_pending=True)
    if user.email:
        profile.send_email("Information about Agda email address change",
                           "agda/account/inform_change_email.txt",
                           use_email_pending=False)
    msg = "You have requested an email address change. Confirmation email sent to new address <b>%(new)s</b>"
    if user.email:
        msg += " Notification email sent to old address <b>%(old)s</b>"
    msg += '.'
    messages.info(request, mark_safe(msg % dict(old=user.email, new=profile.email)))
    return redirect(top)


@never_cache
def account_confirm_email(request, profile_id, confirmation_code):
    """Handle email address confirmation URL."""
    user = request.user
    profile = user
    if profile.valid:
        return render(request, 'agda/account/confirm_email.html')

    # Check if the confirmation code works
    code_ok = profile.check_email_confirmation_code(confirmation_code)

    # Check that this email_pending is not the confirmed email of another User
    users = User.objects.filter(username=profile.email)
    if users and (len(users) > 1 or users[0] != profile):
        code_ok = False

    if code_ok and request.POST.get("confirmed"):
        # Register the email as confirmed, and the account therefore as valid.
        user.username = profile.email
        user.save()
        profile.save()
        profile.log_change(profile, message="Agda: Email %s confirmed, user level now %s." % (user.username))
        profile.send_email("%s %s: Agda account created" % (user.first_name, user.last_name),
                           "agda/account/validated_email.txt",
                           cc_recipients=[settings.AGDA_MAIL_WATCHERS])
        # Redirect with message
        messages.success(request, "Your email address has now been confirmed.")
        return redirect(top)

    logger.warn("Failed email confirmation for profile %s." % profile)
    return render(request, 'agda/account/confirm_email.html', dict(code_ok=code_ok, confirmed=False))


class AccountChangePasswordForm(forms.Form):
    # Max password length same as User.email max_length
    old_password = forms.CharField(max_length=email_max_length, widget=forms.PasswordInput(render_value=True), label="Old Password")
    password1 = forms.CharField(max_length=email_max_length, widget=forms.PasswordInput(render_value=True), label="New Password")
    password2 = forms.CharField(max_length=email_max_length, widget=forms.PasswordInput(render_value=True), label="New Password (again)")

    def __init__(self, *args, **kw):
        self.user = kw.pop('user', None)
        super(AccountChangePasswordForm, self).__init__(*args, **kw)

agda/templates/agda/account/api_password_disable.html
{% extends "base.html" %}

{% block title %}{{ block.super }} disable api password {% endblock %}

{% block content_title %}
	Disable api password
{% endblock %}

{% block content %}

<p>To access the Agda RESTful web service api you need to have an api password. 
{% if not user.has_usable_api_password %}
You currently do not have one.
{% else %}
Click the button below to disable your Agda api password.

<p>Note that if you click the button below your Agda api password will be disabled, 
so any scripts that you may have that are still using the old password will be locked out 
until you have generated a new api password and updated them. 

<form method="POST">{% csrf_token %}<input type="submit" value="Disable api password"></form>

{% endif %}

{% endblock %}

agda/templates/agda/account/api_password_reset.html
{% extends "base.html" %}

{% block title %}{{ block.super }} api password reset{% endblock %}

{% block content_title %}
{% if api_password %}
	New api password
{% else %}
	Reset api password
{% endif %}
{% endblock %}

{% block content %}

{% if api_password %}
	{% if modified %}
		<p>Your Agda api password has now been reset. Note that your old password has been overwritten, 
		so any scripts that you may have that are still using the old password will be locked out until 
		you have updated them.
	{% else %}
		<p>A new Agda api password has now been created for you.
	{% endif %}
	<p><span class="important">New password:</span> {{ api_password }}
	<h2>Important notes</h2>
	<p>Note that this is the only time that Agda will display this password. 
	Take special care to note it down, as there is no chance of recovering it if you lose it.
	<p>Agda api passwords <span class="important">must not</span> be stored in a web browser. 
	This is to prevent <a href="https://www.google.com/search?q=cross-site+request+forgery">cross-site request forgery</a> attacks.
	<p>Agda api passwords <span class="important">must</span> be stored securely and privately. 
	It is sufficient to save it in a file that only you have read access to (on linux: chmod 600).
	<p>Please note that reloading this page will generate a new password.
	
{% else %}

	<p>To access the Agda RESTful web service api you need to have an api password. {% if not user.has_usable_api_password %}You currently do not have one set.{% endif %}
	
	<h2>Agda api password rules</h2>
	
	<p>Agda api passwords <span class="important">must not</span> be stored in a web browser. 
	This is to prevent <a href="https://www.google.com/search?q=cross-site+request+forgery">cross-site request forgery</a> attacks.
	<p>Agda api passwords <span class="important">must</span> be stored securely and privately. 
	It is sufficient to save it in a file that only you have read access to (on linux: chmod 600).
	
	{% if user.has_usable_api_password %}
		<p>Note that if you click the button below your old password will be overwritten, so any scripts that you may have that are still using the old password will be locked out until you have updated them. 
	{% endif %}
	
	<form method="POST">{% csrf_token %}<input type="submit" value="Generate new password"></form>

{% endif %}

{% endblock %}

agda/templates/agda/account/change_email.html
{% extends "base.html" %}

{% block title %}Change email address{% endblock %}

{% block content_title %}Change email address{% endblock %}

{% block content %}

<div>
<P>You will receive an email when you submit the change.
You need to follow the instructions in that email to confirm your email address change. 
Until your email address is confirmed you can still login using your old email address, but your account will not have full privileges.
</div>

{% with "Change email address" as editform_submit_value %}
  {% include "agda/editform.html" %}
{% endwith %}

{% endblock %}

agda/templates/agda/account/change_password.html
{% extends "base.html" %}

{% block title %} {{ block.super }} Change password {% endblock %}

{% block content_title %} Change password {% endblock %}

{% block content %}

{{ success }}

{% include "agda/editform.html" %}

{% endblock %}

agda/templates/agda/account/confirm_email.html
{% extends "base.html" %}
{% load agda_tags %}

{% block title %}Confirm Email Address{% endblock %}

{% block content_title %}Confirm Email Address{% endblock %}

{% block content %}

{% if code_ok %}
    <P>Please confirm your email adress <B>{{ user.email_pending|mailto_link }}</B> using the button below.

    <FORM method="POST">{% csrf_token %}
      <INPUT TYPE="hidden" NAME="confirmed" VALUE="yes">
      <INPUT TYPE="submit" VALUE="Confirm Email Address">
    </FORM>
{% else %}
  <p>Your email address <B>could not be confirmed</B>. Perhaps you have already confirmed the address, or the confirmation code is wrong or too old?
{% endif %}


{% endblock %}

agda/templates/agda/account/edit.html
{% extends "base.html" %}

{% load agda_tags %}

{% block title %}User profile for {{ user.name }}{% endblock title %}

{% block content_title %}{{ user.name }} User Profile {% endblock content_title %}

{% block content %}

<div class="editform">
<form method="post">
{% csrf_token %}
<h1>User information</h1>
<p>You will receive an email confirmation to <B>{{ user.email }}</B> when you save your changes.
<p>Field marked with an asterisk (<SPAN CLASS="reqfield">*</SPAN>) are required. 
<table class="fieldlist">
  <col><col><col class="expand">
  <tr>
    <td class="editerror" colspan="3">
	    {% for e in form.non_field_errors %}
	        <div class="errorlist">{{ e }}</div><br>
	    {% endfor %}
    </td>
  </tr>

  <tr class="editfield">
    <td class="editlabel"><span title="This is also your login username.">Email address:</span></td>
    <td class="editvalue" colspan="2">
    	<span title="This is your email.">{{ user.email }}</span> 
    		&nbsp;&mdash;&nbsp;
    		<a href="{% url 'profiles.views.account_change_email' %}">Change</a>
    </td>
  </tr>      
  <tr class="editfield-last"><td></td><td class="editcomment" colspan="2"></td></tr>

  <tr class="editfield">
    <td class="editlabel">Password:</td>
    <td class="editvalue" colspan="2">Enabled &nbsp;&mdash;&nbsp; <a href="{% url 'profiles.views.account_change_password' %}">Change password</a></td>
  </tr>
  <tr class="editfield-last"><td></td><td class="editcomment" colspan="2"></td></tr>

  <tr class="editfield">
    <td class="editlabel" title="Separate login password for access to the Agda RESTful web service api.">Api password:</td>
    <td class="editvalue" colspan="2">
    	{% if user.has_usable_api_password %}
    		<span title="Separate login password for access to the Agda RESTful web service api.">Enabled &nbsp;&mdash;&nbsp;</span> 
    		<a href="{% url 'profiles.views.account_api_password_reset' %}">Generate new</a> / 
    		<a href="{% url 'profiles.views.account_api_password_disable' %}">Disable</a> 
    	{% else %}
    		<span title="Separate login password for access to the Agda RESTful web service api.">Disabled</span> &nbsp;&mdash;&nbsp; 
    		<a href="{% url 'profiles.views.account_api_password_reset' %}">Generate new</a>
    	{% endif %}
    </td>
  </tr>
  <tr class="editfield-last"><td></td><td class="editcomment" colspan="2"></td></tr>

  <tr class="editfield-last"><td></td><td class="editcomment" colspan="2"></td></tr>

  <tr class="editfield-last"><td></td><td class="editcomment" colspan="2"></td></tr>

  <tr class="editfield">
    <td class="editlabel"><label for="id_first_name">First name</label>: {% if form.first_name.field.required %}<SPAN CLASS="reqfield">*</SPAN>{% endif %}</td>
    <td class="editvalue">{{ form.first_name }}</td>
    <td class="editerror">{% for e in form.first_name.errors %}<div class="errorlist">{{ e }}</div>{% endfor %}</td>
  </tr>      
  <tr class="editfield-last"><td></td><td class="editcomment" colspan="2">{{ form.first_name.help_text }}</td></tr>

  <tr class="editfield">
    <td class="editlabel"><label for="id_last_name">Last name</label>: {% if form.last_name.field.required %}<SPAN CLASS="reqfield">*</SPAN>{% endif %}</td>
    <td class="editvalue">{{ form.last_name }}</td>
    <td class="editerror">{% for e in form.last_name.errors %}<div class="errorlist">{{ e }}</div>{% endfor %}</td>
  </tr>      
  <tr class="editfield-last"><td></td><td class="editcomment" colspan="2">{{ form.last_name.help_text }}</td></tr>

  <tr><td colspan="2" class="editsubmit"><input type="submit" value="Save changes" /></td></tr>
</table>
</form>
</div>
{% endblock content %}